<?php

namespace App\Services\Core\PrintTemplate;

use App\Models\Core\Currency;
use App\Models\Core\Preference;
use App\Models\Core\PrintTemplate;
use App\Services\Handlebar\ArithmeticHelperService;
use App\Services\Handlebar\FormatHelperService;
use App\Services\Handlebar\LabelHelperService;
use App\Utils;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use LightnCandy\LightnCandy;

/**
 * Renders a print-template document into HTML entirely server-side (PHP),
 * without a browser. This is the PHP counterpart of
 * `resources/js/Pages/Core/Components/PrintPreview.jsx` +
 * `resources/js/lib/initHandlebar.js` — used where a browser/iframe is not
 * available (e.g. auto-attaching a PDF when a document finishes approval).
 *
 * Deliberately not guaranteed to be byte-identical to the JS render; see
 * design.md "Keputusan yang Sudah Dikonfirmasi" for why a formal parity
 * check between the two implementations is out of scope.
 */
class PrintTemplateRenderService {
    public function __construct(
        protected LabelHelperService $labelHelper,
        protected FormatHelperService $formatHelper,
        protected ArithmeticHelperService $arithmeticHelper,
    ) {}

    /**
     * Render a document + its print template into a full HTML string,
     * including the letter head when configured, mirroring the `html`
     * produced by `PrintPreview.jsx`.
     *
     * @param  array<string, mixed>  $columns  Same shape as `PrintTemplate::columns` accessor.
     */
    public function render(Model $doc, PrintTemplate $template, array $columns, array $docInfo = []): string {
        $preferences         = $this->resolvePreferences();
        $defaultCurrencyCode = $preferences['default_currency_id'] ?? null;

        $data = $this->formatData($doc->toArray(), $columns, [
            'model'               => $template->model,
            'lang'                => $template->default_language ?? 'en',
            'absoluteNumber'      => (bool) $template->show_absolute_values,
            'defaultCurrencyCode' => $defaultCurrencyCode,
            'currencySymbols'     => $this->resolveCurrencySymbols($columns, $defaultCurrencyCode),
        ]);

        $context = [
            'lang'     => $template->default_language ?? 'en',
            'modelDoc' => $template->model,
            'columns'  => $columns,
            'company'  => $preferences,
            'docInfo'  => $docInfo,
            'document' => $doc,
            'doc'      => $data,
        ];

        $html = '';

        if (! $template->is_letter_head && $template->letterHead) {
            $letterHead = $template->letterHead;
            $html .= $this->compileHandlebars(
                str_replace('body', 'div', $letterHead->html ?? ''),
                $context,
            );
        }

        $html .= $this->compileHandlebars(
            str_replace('body', 'main', $template->html ?? ''),
            $context,
        );

        return $html;
    }

    /**
     * Compile a Handlebars template source with this service's helper set
     * and render it against the given context.
     *
     * lightncandy compiles Handlebars into a PHP source string rather than
     * rendering directly — eval() turns that source into a callable
     * renderer, which is then invoked with the context.
     *
     * @param  array<string, mixed>  $context
     */
    protected function compileHandlebars(string $templateSource, array $context): string {
        if (trim($templateSource) === '') {
            return '';
        }

        $phpCode = LightnCandy::compile($templateSource, [
            'flags'   => LightnCandy::FLAG_HANDLEBARSJS | LightnCandy::FLAG_ERROR_LOG,
            'helpers' => $this->helpers(),
        ]);

        if ($phpCode === false) {
            return '';
        }

        // eval() here runs PHP source *generated by lightncandy's own
        // compiler* from the Handlebars template — this is how lightncandy
        // is designed to be used (compile() returns source, not a callable;
        // see its README). It is not evaluating arbitrary user input: the
        // Handlebars source (`PrintTemplate.html`/`letterHead.html`) is
        // authored through the internal print-template editor by
        // authenticated staff with template-edit permission, not by
        // arbitrary end users — the same trust boundary that already
        // applies to the existing client-side `Handlebars.compile()` call
        // in PrintPreview.jsx, which this method mirrors server-side.
        $renderer = eval($phpCode);

        if (! is_callable($renderer)) {
            return '';
        }

        return $renderer($context);
    }

    /**
     * @return array<string, callable>
     */
    protected function helpers(): array {
        return [
            'relation' => fn ($payload) => Utils::convertTemplateLink($payload),
            'label'    => fn ($path, $options) => $this->labelHelper->getLabel(
                (string) $path,
                $options['data']['root']['columns'] ?? [],
                $options['data']['root']['lang'] ?? 'en',
            ),
            'trans'         => fn ($payload) => is_string($payload) ? __($payload) : ($payload['title'] ?? __($payload['titleTrans'] ?? '') ?? $payload['name'] ?? ''),
            'companyDetail' => fn ($key, $options) => $options['data']['root']['company'][$key] ?? '',
            // No custom `each` override here (unlike initHandlebar.js, which
            // overrides {{#each}} solely to inject a 1-based `idx` onto each
            // item). lightncandy compiles {{#each}} as a builtin block
            // construct rather than a plain registered helper, so redefining
            // it under `helpers` risks silently not taking effect or
            // conflicting with the compiled builtin. `idx` is instead
            // injected directly onto array items during formatData() (see
            // below), so templates using {{this.idx}} inside {{#each}}
            // still work without needing to override the block helper.
            'infoColumns' => function ($context, $options) {
                if (! $context) {
                    return $options['fn']($context);
                }
                $type   = $options['hash']['type'] ?? 'data';
                $oriKey = $options['hash']['key'] ?? '';
                $data   = collect($context)->firstWhere('type', $type)['columns'] ?? null;

                foreach (array_filter(explode('.', $oriKey)) as $key) {
                    $data = collect($data ?? [])->firstWhere('name', $key)['columns'] ?? null;
                }

                $reduced = collect($data ?? [])->mapWithKeys(fn ($col) => [
                    $col['name'] => ($options['hash']['extract'] ?? null) ? ($col[$options['hash']['extract']] ?? null) : $col,
                ])->all();

                return $options['fn']($reduced);
            },
            'formatDate'     => fn ($value, $format) => $this->formatHelper->formatDate($value, $format),
            'formatCurrency' => fn ($value, $currency) => $this->formatHelper->formatCurrency($value, $currency),
            'formatNumber'   => fn ($value, $decimals) => $this->formatHelper->formatNumber($value, (int) $decimals),
            'uppercase'      => fn ($value) => is_string($value) ? mb_strtoupper($value) : '',
            'multiply'       => fn ($a, $b) => $this->arithmeticHelper->multiply($a, $b),
            'subtract'       => fn ($a, $b) => $this->arithmeticHelper->subtract($a, $b),
            'add'            => fn ($a, $b) => $this->arithmeticHelper->add($a, $b),
            'divide'         => fn ($a, $b) => $this->arithmeticHelper->divide($a, $b),
        ];
    }

    /**
     * PHP port of formatData() in PrintPreview.jsx — formats a document's
     * raw field values per column type (relation, date/time/datetime,
     * boolean, formStatus, string, currency/number) so they render the same
     * way the client-side preview does.
     *
     * Also injects a 1-based `idx` onto items of any `relations` (array)
     * field, since this render path does not override the Handlebars
     * `{{#each}}` block helper (see helpers() for why) — this is the PHP
     * equivalent of `context[i].idx = i + 1` in the JS `each` override.
     *
     * @param  array<string, mixed>  $data
     * @param  array<string, mixed>  $columns
     * @param  array{model?: string, lang?: string, absoluteNumber?: bool, defaultCurrencyCode?: mixed, currencySymbols?: array<string, string>}  $opts
     * @return array<string, mixed>
     */
    protected function formatData(array $data, array $columns, array $opts = []): array {
        $cols = $columns[$opts['model'] ?? ''] ?? null;
        if ($cols === null) {
            return $data;
        }

        $newData = [];

        foreach ($data as $key => $value) {
            if ($key === 'templateLink') {
                $newData[$key] = $value;

                continue;
            }

            $col = $cols[$key] ?? null;
            if ($col === null) {
                continue;
            }

            $newData[$key] = match ($col['type'] ?? null) {
                'relation'  => $this->formatData((array) $value, $columns, [...$opts, 'model' => $col['related']]),
                'relations' => array_values(array_map(
                    fn ($item, $index) => [
                        ...$this->formatData((array) $item, $columns, [...$opts, 'model' => $col['related']]),
                        'idx' => $index + 1,
                    ],
                    (array) $value,
                    array_keys((array) $value),
                )),
                'date', 'time', 'datetime' => $this->formatDateTimeValue($value, $col['type'], $opts['lang'] ?? 'en'),
                'boolean'    => "<input type='checkbox' " . ($value ? 'checked' : '') . '>',
                'formStatus' => __("status.{$value}"),
                'string'     => $this->formatStringValue($value, $col),
                'currency', 'number' => $this->formatNumericValue($value, $col, $data, $opts),
                default => $value,
            };
        }

        return $newData;
    }

    protected function formatDateTimeValue(mixed $value, string $type, string $lang): string {
        if ($value === null || $value === '') {
            return '';
        }

        $date = Carbon::parse((string) $value, 'UTC')->locale($lang);

        return match ($type) {
            'date'  => $date->translatedFormat('d F Y'),
            'time'  => $date->translatedFormat('H:i'),
            default => $date->translatedFormat('d F Y H:i'),
        };
    }

    /**
     * @param  array<string, mixed>  $col
     */
    protected function formatStringValue(mixed $value, array $col): mixed {
        if (isset($col['valueTrans'])) {
            return __("{$col['valueTrans']}.{$value}");
        }
        if (isset($col['parse'])) {
            return $col['parse'][(string) $value] ?? '';
        }

        return $value;
    }

    /**
     * @param  array<string, mixed>  $col
     * @param  array<string, mixed>  $rowData
     * @param  array<string, mixed>  $opts
     */
    protected function formatNumericValue(mixed $value, array $col, array $rowData, array $opts): mixed {
        if (! is_numeric($value)) {
            return $value;
        }

        $number = (float) $value;
        if ($opts['absoluteNumber'] ?? false) {
            $number = abs($number);
        }

        $prefix = '';
        if (($col['type'] ?? null) === 'currency') {
            $symbol = $this->resolveCurrencySymbol($col, $rowData, $opts);
            $prefix = $symbol !== '' ? "{$symbol} " : '';
        }

        return $this->formatHelper->formatNumber($number, (int) ($col['decimalScale'] ?? 0)) === ''
            ? $number
            : $prefix . $this->formatHelper->formatNumber($number, (int) ($col['decimalScale'] ?? 0));
    }

    /**
     * PHP port of resolveCurrencySymbol() in PrintPreview.jsx — resolution
     * precedence: column's own currencyCode → row's `currency` field →
     * the document's default currency.
     *
     * @param  array<string, mixed>  $col
     * @param  array<string, mixed>  $data
     * @param  array<string, mixed>  $opts
     */
    protected function resolveCurrencySymbol(array $col, array $data, array $opts): string {
        $symbols = $opts['currencySymbols'] ?? [];

        $colCurrency = $col['currencyCode'] ?? null;
        if ($colCurrency) {
            return is_array($colCurrency)
                ? ($colCurrency['symbol'] ?? $symbols[$colCurrency['code']] ?? '')
                : ($symbols[$colCurrency] ?? '');
        }

        $rowCurrency = $data['currency'] ?? null;
        if ($rowCurrency) {
            return is_array($rowCurrency)
                ? ($rowCurrency['symbol'] ?? $symbols[$rowCurrency['code']] ?? '')
                : ($symbols[$rowCurrency] ?? '');
        }

        return $symbols[$opts['defaultCurrencyCode'] ?? ''] ?? '';
    }

    /**
     * PHP port of collectCurrencyCodes() + the synchronous symbol lookup
     * that replaces PrintPreview.jsx's async getCurrencyConfig() call —
     * server-side rendering has no equivalent of a React effect, so symbols
     * are resolved with one query up front instead.
     *
     * @param  array<string, mixed>  $columns
     * @return array<string, string>
     */
    protected function resolveCurrencySymbols(array $columns, mixed $defaultCurrencyCode): array {
        $codes = [];

        foreach ($columns as $modelColumns) {
            if (! is_array($modelColumns)) {
                continue;
            }
            foreach ($modelColumns as $col) {
                if (($col['type'] ?? null) !== 'currency') {
                    continue;
                }
                $cc = $col['currencyCode'] ?? null;
                if (is_string($cc) && $cc !== '') {
                    $codes[] = $cc;
                } elseif (is_array($cc) && ! empty($cc['code']) && empty($cc['symbol'])) {
                    $codes[] = $cc['code'];
                }
            }
        }

        if ($defaultCurrencyCode) {
            $codes[] = $defaultCurrencyCode;
        }

        if (empty($codes)) {
            return [];
        }

        return Currency::query()->whereIn('code', array_unique($codes))->pluck('symbol', 'code')->all();
    }

    /**
     * @return array<string, mixed>
     */
    protected function resolvePreferences(): array {
        return Preference::query()->pluck('value', 'key')->all();
    }
}
